Medium/Swap Nodes In Pairs

Solution to leetcode question, Swap Nodes in Pairs.
Please add a hacktoberfest accepted label.

Create Swap Nodes In Pairs

---

Medium/Remove Duplicates from Sorted Array/solution.cpp

added c++ code to remove duplicate from sorted array

Remove Duplicates from Sorted Array

---

Easy/MergeArray.java
Medium/KadaneAlgo.java

To find the maximum sum of subarray

Maximum Subarray

---

Medium/stringCompression.cpp

Added solution for LC problem : 443. String Compression
Problem Link:
https://leetcode.com/problems/string-compression/

Added solution for LC problem : 443. String Compression

---

Easy/Factorial.java

Using this Program you can find Factorial of each number.

Factorial.java

---

Easy/Inheritance.java

Inheritance program for beginners

Inheritance.java

---

Hard/BubbleSort.java

BubbleSort.java

---

Medium/LargestnumberofArray.java

LargestnumberofArray.java

---

Easy/PrimeNumber.java

Find Prime Number using this program.
Beginners program

PrimeNumber.java

---

Easy/EvenOddNumber.java

EvenOddNumber.java

---

Medium/Armstrongnumber.java

Find Armstrong number using this Program.

Armstrongnumber.java

---

Easy/Add_Binary.cpp

Added Code for LeetCode 67. Add Binary Question

67. Add Binary

---

Medium/2425. Bitwise XOR of All Pairings.cpp

Leetcode question 2425 Bitwise XOR of All Pairings: cpp solution added .
Please mark thi as hacktober fest accepted.

2425 Bitwise XOR of All Pairings: cpp solution added

---

Hard/skyline.java

added skyline.java

---

Medium/Subarray Sum Equals K.cpp

please review my work and let me know if you want any other changes

added Subarray Sum Equals K solution

---

Medium/91/ Decode Way/Solution.java

#39 - Add java solution of 91. Decode Ways

---

Easy/FizzBuzz.js

how to solve fizz buzz in leetcode

add fizzbuzz

---

Medium/numRollsToTarget.py

Kindly review & merge followed by providing hacktoberFest2022 acceptance tag.

numRollsToTarget

---

Easy/217. Contains Duplicate

Added leetcode easy question with python solution and it is 96% faster using dict. Please review it and tell me if some changes needed.

217. Contains duplicate

---

121. Best Time to Buy and Sell Stock

Added leetcode easy 121. Best Time to Buy and Sell Stock question, this is most asked question in MAANG interviews, kindly go through the question.

121. Best Time to Buy and Sell Stock

---

Medium/2428. Maximum Sum of an Hourglass.cpp

2428 Maximum Sum of an Hour Glass : cpp solution added of Leetcode.
Please mark this as Hacktober Fest accepted.

2428 Maximum Sum of an Hour Glass : cpp solution added

---

Easy/quick_sort.cpp

Hi! I added a Quick sort program in C++ using Recursion. Please accept my Request.

Quick Sort Program in C++ using Recursion

---

Medium/78. Subsets

Added Leetcode medium 78. Subsets, important for interviews

78. Subsets

---

Medium/DecodeWays.java

Kindly review DecodeWays.java of leetcode!

Added DecodeWays

---

Easy/Best_Time_to_Buy_and_Sell_Stock.cpp

Added cpp solution of the most famous question asked in MAANG.

Intuition added

---

Easy/Ransom Note.cpp

Add this solution in **Easy folder**

Create Ransom Note.cpp

---

Medium/91/ Decode Way/Solution.py

#40 - Add python solution of 91. Decode Ways

---

Hard/Maximum Deletions on a String.cpp

Added the solution of Weekly Contest 313 hard question.

Weekly Contest 313

---

Easy/2367. Number of Arithmetic Triplets.cpp
Hard/336. Palindrome Pairs.cpp

added two leetcode problems one easy and one hard

add leetcode ques

---

Easy/Length_of_last_word.cpp
Easy/Problem_69.Sqrt(x).cpp

This is a CPP Solution of Problem No.58
This closes issue #87

Solution for Problem.58 

---

Easy/876. Middle of the Linked List.py

middle of the linked list in python

leetcode easy problem

---

Easy/Maximum Product of Three Numbers.cpp

added Maximum Product of Three Numbers solution

---

Medium/1155/ Number of Dice Rolls With Target Sum/Solution.java

#79 - Add java solution for 1155. Number of Dice Rolls With Target Sum

---

Easy/Remove Duplicates from Sorted Array.cpp

Remove duplicate

---

Medium/695. Max Area of Island.cpp

added 695. Max Area of Island leetcode

added medium leetcode

---

main (3).cpp

I also solve this question on leetcode 
thankyou for assign me this issue

Update main (3).cpp

---

Medium/1155/ Number of Dice Rolls With Target Sum/Solution.py

#80 - Add python solution for 1155. Number of Dice Rolls With Target Sum

---

Easy/101. Symmetric Tree

added the solution to question of 101, to check if the tree is symmetric or not.

Create 101. Symmetric Tree

---

Medium/Minimum_Absolute_Sum_Difference.cpp

Kindly merge this into the repo for Hacktoberfest. 
Cheers :)

Solved issue #128 Add Minimum_Absolute_Sum_Difference to the repo

---

Medium/RemoveNthNodeFromEnd.cpp

I have added the C++ code on removing nth node from end of linked list with comments for better understanding

Added the code on Removing Nth Node from End of Linked List

---

Medium/flattenBTtoLL.cpp

ADDED SOLUTION FOR LC PROBLEM : 114. Flatten Binary Tree to Linked List
Problem link:
https://leetcode.com/problems/flatten-binary-tree-to-linked-list/

ADDED SOLUTION FOR LC PROBLEM : 114. Flatten Binary Tree to Linked List

---

Medium/852.Peakindex.cpp

Runtime: 371 ms
Memory Usage: 59.6 MB

Create 852.Peak Index in a Mountain Array

---

Hard/Array_Divisible.cpp

Weekly Contest 302 
Question tag : Hard
Question Name : Minimum Deletions to Make Array Divisible

Weekly Contest 302

---

Hard/Count Subarrays.cpp

Question Name : Count Subarrays With Score Less Than K
Question Tag : Hard

Biweekly Contest 80

---

Hard/first_missing_positive.cpp

Hey **@Vanshika2063** ,
Added First Missing Positive **Leetcode Hard Problem**.
Please review and merge.
**Thanks.**

Added First Missing Positive Leetcode Hard Problem

---

Medium/62.Unique_paths.cpp

Leetcode (62) added

---

Easy/Create Maximum sum subarray of size k.cpp

Added the code for Create Maximum sum subarray of size k , pls check and merge it.

Create Create Maximum sum subarray of size k.cpp

---

Hard/Minimum Weighted Subgraph With the Required Paths

I have solved a Problem Create Minimum Weighted Subgraph With the Required Paths

Create Minimum Weighted Subgraph With the Required Paths

---

Easy/Two_sum.cpp

Hey , i have added two sum in the file, please merge my PR

Added Two Sum

---

Medium/Spiral_Matrix.java

Added code for Spiral_Matrix program in Java (Leetcode Medium).
Kindly review and merge it ASAP.

added spiral_matrix in java

---

Easy/LinkedList_Cycle.py

Kindly consider the pull request, thanks.

Added Linked List Cycle in Python

---

Easy/plusOne.js

Using Javascript added program for plusOne

added program for plusOne

---

Medium/34. Find First and Last Position of Element in Sorted Array.java

Solved in O(log n) using binary search approach.

Added solution to find first and last position of element in sorted array

---

Hard/Scramble_String.cpp

Added Scramble String Ques. regarding issue #188

Added Scramble String Ques. regarding issue #188

---

Easy/Path Sum.cpp

4th October Daily LeetCode Challenge
Question Name : Path Sum
Question Tag : Easy

Daily LeetCode Challenge

---

Hard/37. Sudoku Solver.py

Added code with comments for the famous problem - Sudoku Solver ( LC hard )

Create 37. Sudoku Solver.py

---

Hard/44. Wildcard Matching.py

Added code for LC Hard Question WildCard Matching

Create 44. Wildcard Matching.py

---

Easy/94. Binary_Tree_Inorder_Traversal.py

added code for https://leetcode.com/problems/binary-tree-inorder-traversal/

Create 94. Binary_Tree_Inorder_Traversal.py

---

Hard/140. Word Break II.py

Added Code for LC Hard Problem - Word Break

Create 140. Word Break II.py

---

Easy/101. Symmetric_Tree.py

added code for https://leetcode.com/problems/symmetric-tree/

Create 101. Symmetric_Tree.py

---

Easy/RichestCustomerWealthSolution.java
Hard/FindMountainArraySolution.java
Medium/PeakIndexMountainArraySolution.java
Medium/RotateArraySolution.java
Medium/SearchRotatedSortedArray.java

Added solutions to problems #852 # 33 # 189 #1095 and #1672 in JAVA programming language, into respective folders of Easy, Medium and Hard. Kindly review my PR.

Added solutions to leetcode problems in  JAVA propgramming language into respective folders.

---

Hard/Sliding Window Maximum.cpp

I have added  a leetcode hard question. Please merge my pr. Thank you!

Create Sliding Window Maximum.cpp

---

Medium/Max_Bitwise_And.cpp

Question Name : Longest Subarray With Maximum Bitwise AND
Question Tag : Medium

Weekly Contest 312

---

Medium/Remove Duplicates from Sorted Array/Remove Nth Node From End of List.java

Added desired solution

---

Easy/69. Sqrt(x).py

added python code for https://leetcode.com/problems/sqrtx/

Create 69. Sqrt(x).py
